version: '2'
services:
  riak:
    container_name: riak-datastore
    image: altfatterz/riak
    ports:
      - "8087:8087"
      - "8098:8098"
  web:
    container_name: service-using-riak-datastore
    image: altfatterz/riak-sample
    # docker-compose will start services in dependency order. Here mysql service will be started before web
    # depends_on will not wait for mysql to be "ready" before starting "web". If you need a service to be ready see
    # https://docs.docker.com/compose/startup-order/
    depends_on:
      - riak
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080"
      - "8000:8000"
